// TypeScript types mirroring the Supabase schema
// Keep in sync with supabase/migrations/001_initial_schema.sql

export interface Tenant {
  id: string;
  clerk_user_id: string;
  email: string | null;
  created_at: string;
}

export type AdPlatform = 'google' | 'meta' | 'tiktok';

export interface StrategyPlatform {
  name: AdPlatform;
  campaign_types: string[];
  budget_percentage: number;
  reasoning: string;
}

export interface BudgetAnalysis {
  verdict: 'sufficient' | 'too_low' | 'exceeds_ceiling';
  verdict_explanation: string;         // one sentence, plain English
  minimum_monthly_usd: number;         // below this = won't work
  recommended_learning_usd: number;    // first 30 days (higher — accelerate data)
  recommended_steady_usd: number;      // ongoing after learning
  efficiency_ceiling_usd: number;      // above this = diminishing returns
  projected_clicks_monthly: number;    // at recommended_steady budget
  projected_leads_monthly: number;     // at recommended_steady (realistic conversion rate)
  break_even_conversions: number;      // sales needed to cover monthly ad cost
  warnings: string[];                  // specific issues: funnel, audience size, competition, etc.
  platform_exclusions: Array<{ platform: string; reason: string }>; // platforms NOT recommended
}

// Custom performance benchmarks — generated by AI during analysis for this specific client.
// Override the static generic benchmarks in rules.ts.
// Key format: "{platform}_{campaignType}" e.g. "meta_conversions", "google_search"
export interface CustomBenchmark {
  minCtr: number;           // below = underperforming (client-specific)
  goodCtr: number;          // above = strong, eligible to scale
  maxCpc?: number;          // cost per click ceiling
  maxCpa?: number;          // cost per acquisition ceiling (if goal = leads/purchases)
  minDataClicks?: number;   // clicks needed before budget decisions
  learningDays?: number;    // days before budget scaling starts
  rationale: string;        // why these numbers make sense for this client
}

export type CustomBenchmarks = Record<string, CustomBenchmark>;

export interface SocialPlatformPlan {
  platform: 'facebook' | 'instagram' | 'tiktok';
  rationale: string;
  cost_usd: number;
}

export interface SocialPlan {
  recommended: boolean;
  rationale: string;
  platforms: SocialPlatformPlan[];
  content_pillars: string[];
  synergy_with_ads: string;
  estimated_monthly_cost_usd: number;
}

export interface FunnelStrategy {
  awareness: string;
  consideration: string;
  conversion: string;
}

export interface PlatformCreativeBrief {
  platform: string;
  formats: string[];
  quantity_images: number;
  quantity_videos: number;
  hooks: string[];
  cta: string;
}

export interface MissingPlatformSuggestion {
  platform: string;
  reason: string;
  potential_uplift: string;
}

export interface StrategyPlan {
  platforms: StrategyPlatform[];
  market_insights: string;
  target_audience: string;
  estimated_cpc: string;
  recommendations: string;
  past_performance_notes?: string;
  organic_recommendations?: string[];
  budget_analysis?: BudgetAnalysis;
  custom_benchmarks?: CustomBenchmarks;
  social_plan?: SocialPlan;
  // Strategic depth — added per product feedback
  strategy_narrative?: string;
  funnel_strategy?: FunnelStrategy;
  creative_brief?: PlatformCreativeBrief[];
  missing_platforms?: MissingPlatformSuggestion[];
  // Agency brain extension — generated lazily by POST /onboarding/creative-brief
  creative_brief_extended?: CreativeBriefExtended;
  creative_brief_extended_at?: string; // ISO timestamp
  // Intellectual honesty layer — confidence, risks, source attribution
  confidence_scores?: StrategyConfidenceScores;
  confidence_notes?: StrategyConfidenceNotes;
  risk_factors?: StrategyRiskFactor[];
  budget_split_rationale?: string;
  what_we_dont_know?: string[];
  counter_argument?: string;
  // Statistics source attribution — verified claims only
  cited_stats?: Array<{ claim: string; source: string; confidence: 'high' | 'medium' }>;
  // ICP confidence gap — one sentence on what additional info would improve accuracy
  icp_confidence_gap?: string;
}

export interface StrategyConfidenceScores {
  icp: number;      // 0-100
  channel: number;  // 0-100
  budget: number;   // 0-100
  overall: number;  // 0-100
}

export interface StrategyConfidenceNotes {
  icp?: string;
  channel?: string;
  budget?: string;
  overall?: string;
}

export interface StrategyRiskFactor {
  risk: string;
  probability: 'low' | 'medium' | 'high';
  impact: 'low' | 'medium' | 'high';
  mitigation: string;
}

// ── Agency Brain: Extended Creative Brief ────────────────────────────────────
// Generated on-demand (lazy) by POST /onboarding/creative-brief.
// Simulates an expert panel: copywriter + creative director + media planner + industry expert.

export interface MessagingPillar {
  pillar: string;          // e.g. "pain_relief", "social_proof", "transformation"
  headline: string;
  hook: string;
  body: string;
  cta: string;
}

export interface ToneGuide {
  voice: string;           // e.g. "confident, warm, jargon-free"
  examples: string[];      // 2-3 on-brand sample phrases
  avoid: string[];         // phrases/tones to avoid
}

export interface PlatformHooks {
  google: string[];        // 3 hooks for Google
  meta: string[];          // 3 hooks for Meta
  tiktok: string[];        // 3 hooks for TikTok
}

export interface CreativeConceptItem {
  type: 'animation' | 'cinematic' | 'avatar';
  platform: string;
  concept: string;         // short concept name / label
  script: string;          // paste-ready script or description
  rationale: string;       // why this wins for THIS audience
}

export interface AudienceVariant {
  segment: string;
  message_angle: string;
  hook: string;
  platform: string;
}

export interface TimeStrategy {
  morning: string;
  evening: string;
  weekend: string;
}

export interface CreativeBriefExtended {
  messaging_pillars: MessagingPillar[];  // 3 pillars
  tone_guide: ToneGuide;
  hooks: PlatformHooks;
  creative_concepts: CreativeConceptItem[];  // 3 concepts, each different type
  audience_variants: AudienceVariant[];      // 2-3 variants
  time_strategy: TimeStrategy;
}

export type BusinessType = 'ecommerce' | 'hero_product' | 'lead_gen' | 'saas' | 'general_store';

export interface ClientSettings {
  id: string;
  tenant_id: string;
  website_url: string | null;
  management_percentage: number;
  budget_monthly_ils: number;
  goal: 'leads' | 'purchases' | 'traffic' | 'awareness';
  geo_include: string[];
  geo_exclude: string[];
  exclusions: string | null;
  open_notes: string | null;
  risk_level: 'conservative' | 'balanced' | 'aggressive';
  dayparting_rules: DaypartingRule[];
  strategy_plan: StrategyPlan | null;
  conversation: ConversationMessage[];
  confirmed_at: string | null;
  created_at: string;
  updated_at: string;
  // Conversion Intelligence — Round 1
  business_type: BusinessType;
  margin_pct: number | null;
  hero_product_name: string | null;
  hero_product_margin_pct: number | null;
  shopify_domain: string | null;
  tracking_verified: boolean;
}

export interface ConversionEvent {
  id: string;
  tenant_id: string;
  event_type: 'pageview' | 'lead' | 'purchase' | 'add_to_cart' | 'initiate_checkout';
  url: string | null;
  referrer: string | null;
  gclid: string | null;
  fbclid: string | null;
  ttclid: string | null;
  utm_source: string | null;
  utm_medium: string | null;
  utm_campaign: string | null;
  utm_content: string | null;
  utm_term: string | null;
  value: number | null;
  currency: string | null;
  order_id: string | null;
  campaign_id: string | null;
  platform: string | null;
  ip_hash: string | null;
  user_agent: string | null;
  created_at: string;
}

export interface ShopifyConnection {
  id: string;
  tenant_id: string;
  shop: string;
  access_token: string;
  scopes: string | null;
  webhook_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface TrueRoasData {
  platform_roas: number;           // what the ad platforms claim
  true_roas: number | null;        // calculated from actual Shopify/pixel purchase events
  true_profit: number | null;      // (revenue × margin%) - ad spend
  revenue_tracked: number;         // sum of purchase event values
  conversions_tracked: number;     // count of tracked purchases
  spend: number;                   // total ad spend in period
  margin_pct: number | null;       // gross margin % from settings
  data_source: 'shopify' | 'pixel' | 'none';
  period_days: number;
}

export interface DaypartingRule {
  day: number;        // 0 = Sunday, 6 = Saturday
  start_hour: number; // 0–23
  end_hour: number;   // 0–23
}

export interface ConversationMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

export interface PlatformToken {
  id: string;
  tenant_id: string;
  platform: AdPlatform;
  access_token: string;   // encrypted
  refresh_token: string | null; // encrypted
  expires_at: string | null;
  scope: string | null;
  account_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface AuditLog {
  id: string;
  tenant_id: string;
  action: string;
  platform: AdPlatform | null;
  actor: 'system' | 'user';
  payload: Record<string, unknown>;
  created_at: string;
}

export interface Campaign {
  id: string;
  tenant_id: string;
  platform: AdPlatform;
  external_id: string | null;
  name: string;
  campaign_type: string;
  status: 'pending' | 'active' | 'paused' | 'error';
  daily_budget_usd: number;
  error_message: string | null;
  created_at: string;
  updated_at: string;
}

export interface CreativeJob {
  id: string;
  tenant_id: string;
  campaign_id: string | null;
  type: 'avatar' | 'cinematic' | 'animation';
  platform: AdPlatform | null;
  brief: Record<string, unknown>;
  status: 'queued' | 'processing' | 'completed' | 'failed' | 'pending_setup';
  provider_job_id: string | null;   // HeyGen video_id / Kling task_id / Pika job id
  output_url: string | null;
  revision_of: string | null;
  created_at: string;
  updated_at: string;
}

export type ProtocolType =
  | 'strategy_approval' | 'budget_change' | 'campaign_pause' | 'campaign_resume'
  | 'campaign_scale' | 'creative_refresh' | 'targeting_review' | 'stagnation_alert' | 'general_advice';

export type ProtocolStatus = 'pending' | 'in_discussion' | 'approved' | 'rejected' | 'expired';

export interface ProtocolMessage {
  role: 'vigmis' | 'client';
  content: string;
  timestamp: string;
}

export interface DecisionProtocol {
  id: string;
  tenant_id: string;
  type: ProtocolType;
  status: ProtocolStatus;
  title: string;
  recommendation: string;
  conversation: ProtocolMessage[];
  approval_text: string;
  approval_summary?: string;
  action_payload: Record<string, unknown>;
  campaign_id?: string;
  platform?: string;
  resolved_at?: string;
  expires_at: string;
  created_at: string;
  updated_at: string;
}

export interface ApprovalRequest {
  id: string;
  tenant_id: string;
  action_type: string;
  platform: 'google' | 'meta' | null;
  payload: Record<string, unknown>;
  status: 'pending' | 'approved' | 'rejected' | 'expired';
  reminder_sent_at: string | null;
  decided_at: string | null;
  expires_at: string;
  created_at: string;
}
